import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "../components/client/Header/Navbar";
import ReduxProvider from "../redux/ReduxProvider";
import Preload from "../components/admin/Preload/Preload";
import Footer from "../components/client/Footer/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Misoran Interior BD",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased textured-bg min-h-screen`}>
                <ReduxProvider>
                    <Preload />
                    <Navbar />
                    {children}
                    <Footer />
                </ReduxProvider>
            </body>
        </html>
    );
}
